workspace:
  base: /go
  path: src/github.com/smalex-als/competitions

pipeline:
  build:
    image: golang:${TAG}
    commands:
      - go get
      - go build ./...
      - go test ./...

matrix:
  GO_VERSION:
    - 1.7
    - 1.8
    - latest
