workspace:
  base: /go
  path: src/github.com/smalex-als/competitions

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build ./...
      - go test ./... | grep FAIL | head -n 1
